### ISSUE TITLE
Null exception when selecting an NPC who's got empty spell slots

### ISSUE THREAD

**Issue by shemetz** [reonZ/pf2e-hud#71]
It happened to me after I dragged a spellcaster NPC to the scene and removed some cantrips that it didn't need.  The error being thrown completely prevents the persistent HUD from showing up.

![image](https://github.com/user-attachments/assets/14857cae-8a1e-4186-a037-769b6e91bc88)

```
foundry-esm.js:44349 Uncaught (in promise) Error: Failed to render Application "pf2e-hud-persistent":
Cannot read properties of null (reading 'spell')
[No packages detected]
    at #render (foundry-esm.js:44349:15)
    at async Semaphore._try (foundry-esm.js:6645:19)
Caused by: TypeError: Cannot read properties of null (reading 'spell')
    at checkSpells (shortcuts.ts:623:36)
    at async #i (shortcuts.ts:659:28)
    at async Rr.prepareContext (shortcuts.ts:197:23)
    at async persistent.ts:469:37
    at async Promise.all (index 3)
    at async #render (foundry-esm.js:44340:24)
    at async Semaphore._try (foundry-esm.js:6645:19)
```

points me to this line:
```
                    itemId: active.spell.id,
```

So it's probably fixable with some null handling.

**Comment by reonZ** [comment]
funny because the error message leads me to nowhere on my end :/

![image](https://github.com/user-attachments/assets/614f6e76-9c04-4911-a338-a071d05b280f)
